LoggerClass: de.mknoll.thesis.framework.logger.ConsoleLogger
BaseDirectory: /Users/mimi/Dropbox/Diplomarbeit/Framework/Testruns/
Tests:

########################################
#
# Graph Analysis
#
########################################

  - 
    Activated: 0
    Graph: dipfdbs
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/dipf_dbs
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
  - 
    Activated: 0
    Graph: dnb
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/dnb
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
  - 
    Activated: 0
    Graph: ubka
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/ubka
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
  - 
    Activated: 0
    Graph: ubhd
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/ub_hd
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
  - 
    Activated: 0
    Graph: hsbdo
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/hsb_do
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
  - 
    Activated: 0
    Graph: mpil
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/mpil
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
  - 
    Activated: 0
    Graph: stbhb
    Class: de.mknoll.thesis.tests.analysis.GraphAnalyzer
    PostgresDsn: jdbc:postgresql://localhost/stb_hb
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
    
########################################
#
# Clustering tests
#
########################################    
    
  - 
    Activated: 0
    Graph: dipfdbs
    Class: de.mknoll.thesis.tests.newman.NewmanTest
    PostgresDsn: jdbc:postgresql://localhost/dipf_dbs
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
    Neo4jUrl: http://localhost:7474/db/data/
  - 
    Activated: 1
    Graph: dipfdbs
    Class: de.mknoll.thesis.tests.rgmc.RandomizedGreedyModularityTest
    PostgresDsn: jdbc:postgresql://localhost/dipf_dbs
    PostgresUser: bibtip
    PostgresPassword: bibtip
    PostgresRecTable: recommendationtime
    PostgresDescTable: descriptions
    Neo4jUrl: http://localhost:7474/db/data/
    WriteRecommendationGraphToNeo4j: false
    WriteDendrogramToNeo4j: false
